services:
   questionsapp:
     build:
       context: ./config/
       dockerfile: Dockerfile
       target: base
       args:
         https_proxy: ${HTTPS_PROXY}
         http_proxy: ${HTTP_PROXY}
         HTTPS_PROXY: ${HTTPS_PROXY}
         HTTP_PROXY: ${HTTP_PROXY}
     container_name: questionsapp
     environment:
       - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
       - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
     volumes:
       - ${APP_DIR_HOST}:${APP_DIR_CONTR}
       - ${LOGS_DIR_HOST}:${LOGS_DIR_CONTR}
       - ${ATTACH_DIR_HOST}:${ATTACH_DIR_CONTR}
       - ${DATA_DIR_HOST}:${DATA_DIR_CONTR}
     expose:
       - 8002
     ports:
       - 8002:8002
     env_file:
       - .env
     restart: always
     networks:
       - default
       - service-network
     depends_on:
       - questionsapp_celery
     command: flask run -h 0.0.0.0 -p 8002

   questionsapp_celery:
     build:
       context: ./config/
       dockerfile: Dockerfile
       target: base
       args:
         https_proxy: ${HTTPS_PROXY}
         http_proxy: ${HTTP_PROXY}
         HTTPS_PROXY: ${HTTPS_PROXY}
         HTTP_PROXY: ${HTTP_PROXY}
     container_name: questionsapp_celery
     environment:
       - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
       - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
     volumes:
       - ${APP_DIR_HOST}:${APP_DIR_CONTR}
       - ${LOGS_DIR_HOST}:${LOGS_DIR_CONTR}
       - ${ATTACH_DIR_HOST}:${ATTACH_DIR_CONTR}
       - ${DATA_DIR_HOST}:${DATA_DIR_CONTR}
     restart: always
     env_file:
       - .env
     networks:
       - default
       - service-network
     command: celery --app=celery_worker.celery worker --loglevel=DEBUG

   questionscron:
     build:
       context: ./config/
       dockerfile: Dockerfile
       target: cron
       args:
         https_proxy: ${HTTPS_PROXY}
         http_proxy: ${HTTP_PROXY}
         HTTPS_PROXY: ${HTTPS_PROXY}
         HTTP_PROXY: ${HTTP_PROXY}
     container_name: questionscron
     volumes:
       - ${APP_DIR_HOST}:${APP_DIR_CONTR}
       - ${LOGS_DIR_HOST}:${LOGS_DIR_CONTR}
       - ${ATTACH_DIR_HOST}:${ATTACH_DIR_CONTR}
       - ${DATA_DIR_HOST}:${DATA_DIR_CONTR}
     restart: always
     env_file:
       - .env
     networks:
       - default
       - service-network
     command: cron -f

networks:
  default:
    driver: bridge

  service-network:
    name: service-network
    external: true